### ISSUE TITLE
TypeError: _sasa() takes exactly 6 positional arguments (5 given)

### ISSUE THREAD

**Issue by CX0413ZLP** [dooo12332/AlphaTraj#1]
**I used the xtc, gro files to run the project, it shows Are gromacs' file suitable for Alphatraj?**
(alphatraj) E:\gq_alpha>python E:\AlphaTraj-main\pocket_analysis.py --config ./confi.ini
Control file specified, attempting to load parameters from control file.
single mode
Read traj file...    done.
processing snap shots....
start generate snapshots list(1000:2000:1). This may take a long time...
Processing:   0%|                                                                      | 0.00/1.00k [00:00<?, ?frame/s]
Traceback (most recent call last):
  File "E:\AlphaTraj-main\pocket_analysis.py", line 1238, in <module>
    pa.Analysis(ts,te,to)
  File "E:\AlphaTraj-main\pocket_analysis.py", line 624, in Analysis
    self.snap_shots.Process(start,end,offset,self.rec_mask,self.lig_mask)
  File "E:\AlphaTraj-main\pocket_analysis.py", line 69, in Process
    self.sslist[-1].run(receptor=self.rec,frame=i,rec_mask=rec_mask,lig_mask=lig_mask)
  File "E:\AlphaTraj-main\alphaspace2\Snapshot.py", line 190, in run
    self.genAlphas(receptor,frame,rec_mask)
  File "E:\AlphaTraj-main\alphaspace2\Snapshot.py", line 90, in genAlphas
    self._alpha_space_nonpolar_ratio = _getNonpolarRatio(receptor, alpha_lining_idx=_alpha_lining,frame=frame)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AlphaTraj-main\alphaspace2\functions.py", line 34, in _getNonpolarRatio
    areas = getSASA(protein_snapshot=protein_snapshot,frame=frame)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AlphaTraj-main\alphaspace2\functions.py", line 208, in getSASA
    _geometry._sasa(xyz[frame:frame+1,:,:], radii, int(n_sphere_points), atom_mapping, out)
  File "mdtraj\\geometry\\src\\_geometry.pyx", line 227, in mdtraj.geometry._geometry._sasa
TypeError: _sasa() takes exactly 6 positional arguments (5 given)

**Comment by dooo12332** [comment]
AlphaTraj supports the use of Gromacs topology and trajectory files. Based on the program output, the trajectory file appears to have been successfully loaded. The error seems to occur during the SASA calculation, which might result from incorrect parameter settings or a potential bug in the program. The current information is insufficient. If possible, please provide the config.ini file and describe details about the receptor in your model, along with the numbering information for the receptor and ligand (if present). This will help me locate and resolve the issue. Thank you.

**Comment by CX0413ZLP** [comment]
[GENERAL]
#This tab is used to specify global parameters

# The mode parameter controls the execution mode of the program. 
# There are two options: single and multi. When mode=single, 
# only a single model is processed. When mode=multi, execute the model comparison task
mode=single

# Distance cutoff value when clustering subpockets. The default value is 4.0
#dist_cutoff=4.0

# Whether to use pocket scoring function. If it is not, the pocket volume 
# will be used to rate the pocket. The default value is True
#is_use_score=True

# Characterize the value of hyperparameter n in the sub pocket fluctuation amplitude function. 
# An integer with values ranging from 0 to 100, defaulting to 80
#percentile=80

# Score below score_cutoff sub pockets will not be included in the pocket scoring calculation. The default is 10.0.
#score_cutoff=10.0

#When mode=multi, use this parameter to specify the output file path for pocket matching results.
#pock_pairs=

[MODEL0]
#This tab is used to specify relevant parameters about Model 0

# Path to your topology file
top= ./protein_0_200.gro

# specifies the path to the tracking file. Multiple paths separated by ','
traj= ./md_0_200_protein_no_solvent.xtc

# specifies your receptor protein or ligand residue index. 
# If neither rec_mask nor lig_mask are specified, all atoms are considered as proteins. 
# If rec_mask is not specified but lig_mask is specified, then rec_mask = total_atom - lig_mask.
# (Note: Parameters must appear in pairs.) 
# Format: --rec_mask resn1,resn2,resn3,resn4... 
# Example: If you want to specify residues 1-50, 60 and 70-89 as your receptor protein: 
# "-rec_mask 1,51,60,61,70,90"
#rec_mask=
#lig_mask=


# If you are only interested in a certain region of the protein, you can specify 
# one or more location boxes that wrap around that region. 
# The analysis will be focused within the location boxes, which allows the program output 
# to filter out data you are not interested in.
# At the same time, this can speed up the running of the program and reduce the memory requirements.
# NOTE: To accommodate continuous changes in protein conformation, the box centers are set to 
# the coordinates of a single atom or to the geometric centers of several atoms, 
# which allows the box coordinates to be synchronized with the conformational changes of the protein.
# Format: --box atom1_id,atom2_id length(X-axis direction),width(Y-axis direction),height(Z-axis direction)
# Example: --box 372 18,10,22 458,963 14,12,20


# Specify the starting, ending, and interval of the processed frames
frame_start=10000
frame_stop=20000
#frame_offset=

# The folder where the analysis results are saved
out= E:\gq_alpha\out_put

# Serialized data storage location, not specifying will not save the original data. 
# Suggest saving, you can directly read it later for other analyses, which can greatly save time.
pickle=./raw.dat
#unpickle=

# Control the content of the output
out_summary=true
out_best=true
out_pock_info=true
out_main_best=true
out_coex=true
out_corr=true
out_mtp=true
out_group=true

# Other
# Maximum number of best conformation retention
#best_num=
# Maximum number of best main group conformation retention.
#main_num=

# The file format for pocket information
pock_info_ftype=txt
# In what order are the rows and columns of the coex matrix arranged
coex_sort_by='rank'
# In what order are the rows and columns of the corr matrix arranged
corr_sort_by='rank'

**Comment by CX0413ZLP** [comment]
Thank you for your reply.

[GENERAL]
mode=single
[MODEL0]
top= ./protein_0_200.gro
traj= ./md_0_200_protein_no_solvent.xtc
frame_start=10000
frame_stop=20000
out= E:\gq_alpha\out_put
pickle=./raw.dat
out_summary=true
out_best=true
out_pock_info=true
out_main_best=true
out_coex=true
out_corr=true
out_mtp=true
out_group=true
pock_info_ftype=txt
coex_sort_by='rank'
corr_sort_by='rank'

And i check the code, maybe the atom_selection_mask is lacked?
![2024-12-03 195838](https://github.com/user-attachments/assets/d59e8c6d-5a91-4b1a-bc49-6c1292477e21)

**Comment by dooo12332** [comment]
Either the "lig_mask" or "box" parameter must be specified; otherwise, the program will not know which region of the protein to calculate. This corresponds to the atom_selection_mask parameter in the _sasa function.

**Comment by dooo12332** [comment]
Either the "lig_mask" or "box" parameter must be specified; otherwise, the program will not know which region of the protein to calculate. This corresponds to the atom_selection_mask parameter in the _sasa function.
